### ISSUE TITLE
Provisioning fails with debian-9 image (the default image)

### ISSUE THREAD

**Issue by AlexZeitler** [JonasProgrammer/docker-machine-driver-hetzner#8]
First of all thanks for the work you have done.

I tried to use it on macOS (Docker Machine version 0.13.0) but it fails when provisioning a cloud server:

```
docker-machine create   --driver hetzner   --hetzner-api-token=<token>   test
Running pre-create checks...
Creating machine...
(test) Creating SSH key...
(test) Creating Hetzner server...
(test)  -> Creating server test[503661] in create_server[81420]
(test)  -> Server test[503661]: Waiting to come up...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with debian...
Error creating machine: Error running provisioning: ssh command error:
command : if ! type sudo; then apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y sudo; fi
err     : exit status 100
output  : bash: line 0: type: sudo: not found
Ign:1 http://mirror.hetzner.de/debian/packages stretch InRelease
Get:2 http://mirror.hetzner.de/debian/packages stretch-updates InRelease [91.0 kB]
Ign:3 http://deb.debian.org/debian stretch InRelease
Get:4 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:5 http://mirror.hetzner.de/debian/packages stretch-backports InRelease [91.8 kB]
Get:6 http://mirror.hetzner.de/debian/security stretch/updates InRelease [63.0 kB]
Get:7 http://security.debian.org stretch/updates InRelease [63.0 kB]
Hit:8 http://mirror.hetzner.de/debian/packages stretch Release
Get:9 http://deb.debian.org/debian stretch-backports InRelease [91.8 kB]
Hit:10 http://deb.debian.org/debian stretch Release
Get:11 http://mirror.hetzner.de/debian/packages stretch-updates/main amd64 Packages [7,688 B]
Get:12 http://mirror.hetzner.de/debian/packages stretch-updates/main Translation-en [5,096 B]
Ign:13 http://mirror.hetzner.de/debian/packages stretch-backports/main amd64 Packages
Ign:14 http://mirror.hetzner.de/debian/packages stretch-backports/main Translation-en
Ign:15 http://mirror.hetzner.de/debian/packages stretch-backports/contrib amd64 Packages
Ign:16 http://mirror.hetzner.de/debian/packages stretch-backports/contrib Translation-en
Ign:17 http://mirror.hetzner.de/debian/packages stretch-backports/non-free amd64 Packages
Ign:18 http://mirror.hetzner.de/debian/packages stretch-backports/non-free Translation-en
Get:13 http://mirror.hetzner.de/debian/packages stretch-backports/main amd64 Packages [260 kB]
Get:14 http://mirror.hetzner.de/debian/packages stretch-backports/main Translation-en [182 kB]
Get:15 http://mirror.hetzner.de/debian/packages stretch-backports/contrib amd64 Packages [5,752 B]
Get:16 http://mirror.hetzner.de/debian/packages stretch-backports/contrib Translation-en [4,336 B]
Get:17 http://mirror.hetzner.de/debian/packages stretch-backports/non-free amd64 Packages [17.8 kB]
Get:18 http://mirror.hetzner.de/debian/packages stretch-backports/non-free Translation-en [23.8 kB]
Get:19 http://mirror.hetzner.de/debian/security stretch/updates/main amd64 Packages [269 kB]
Get:20 http://mirror.hetzner.de/debian/security stretch/updates/main Translation-en [118 kB]
Get:21 http://mirror.hetzner.de/debian/security stretch/updates/contrib amd64 Packages [1,352 B]
Get:22 http://deb.debian.org/debian stretch-updates/main amd64 Packages [7,688 B]
Get:23 http://deb.debian.org/debian stretch-updates/main Translation-en [5,096 B]
Get:25 http://deb.debian.org/debian stretch-backports/main amd64 Packages [260 kB]
Get:26 http://deb.debian.org/debian stretch-backports/main Translation-en [182 kB]
Get:27 http://deb.debian.org/debian stretch-backports/contrib amd64 Packages [5,752 B]
Get:28 http://deb.debian.org/debian stretch-backports/contrib Translation-en [4,336 B]
Get:30 http://security.debian.org stretch/updates/main amd64 Packages [269 kB]
Get:31 http://security.debian.org stretch/updates/main Translation-en [118 kB]
Get:32 http://security.debian.org stretch/updates/contrib amd64 Packages [1,352 B]
Fetched 2,239 kB in 2s (866 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  sudo
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 1,055 kB of archives.
After this operation, 3,108 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian stretch/main amd64 sudo amd64 1.8.19p1-2.1 [1,055 kB]
Fetched 1,055 kB in 0s (11.4 MB/s)
Selecting previously unselected package sudo.
(Reading database ... 27470 files and directories currently installed.)
Preparing to unpack .../sudo_1.8.19p1-2.1_amd64.deb ...
Unpacking sudo (1.8.19p1-2.1) ...
Setting up sudo (1.8.19p1-2.1) ...

Configuration file '/etc/sudoers'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** sudoers (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package sudo (--configure):
 end of file on stdin at conffile prompt
Processing triggers for systemd (232-25+deb9u1) ...
Processing triggers for man-db (2.7.6.1-2) ...
Errors were encountered while processing:
 sudo
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by AlexZeitler** [comment]
Looks like this is specific to the `debian-9` image, `--hetzner-image=ubuntu-16.04` works fine.

**Comment by JonasProgrammer** [comment]
I also had this problem when testing, but yes, it's specific to that image. To me it looks like they've had sudo installed in an earlier version of the image, but removed it for production, effectively rendering the headless re-installation impossible due to the overwrite question you see.
I'll try and contact Hetzner support or make a forum post asap.

**Comment by JonasProgrammer** [comment]
After an official statement from a hetzner employee on the forum and re-testing myself, I cannot reproduce this anymore with the latest revision of the `debian-9` image.
Can you please confirm this issue still affects you when provisioning a newly created machine?

**Comment by mxschmitt** [comment]
I'm closing this issue now because we haven't get any update after a week. For any updates regarding this issue feel free to post that or create a new issue. :)

**Comment by tiii** [comment]
I'm still running into this using the latest docker-machine-hetzner-driver (0.2.7) release with docker-machine version 0.13.0, build 9ba6da9 on macOS (10.13.3).

```
$ HETZNER_API_TOKEN=$API_TOKEN docker-machine create --driver hetzner hetzner-docker
Running pre-create checks...
Creating machine...
(hetzner-docker) Creating SSH key...
(hetzner-docker) Creating Hetzner server...
(hetzner-docker)  -> Creating server hetzner-docker[533997] in create_server[226597]
(hetzner-docker)  -> Server hetzner-docker[533997]: Waiting to come up...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with debian...
Error creating machine: Error running provisioning: ssh command error:
command : if ! type sudo; then apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y sudo; fi
err     : exit status 100
output  : bash: line 0: type: sudo: not found
Ign:1 http://mirror.hetzner.de/debian/packages stretch InRelease
Get:2 http://mirror.hetzner.de/debian/packages stretch-updates InRelease [91.0 kB]
Ign:3 http://deb.debian.org/debian stretch InRelease
Get:4 http://security.debian.org stretch/updates InRelease [63.0 kB]
Get:5 http://mirror.hetzner.de/debian/packages stretch-backports InRelease [91.8 kB]
Get:6 http://mirror.hetzner.de/debian/security stretch/updates InRelease [63.0 kB]
Get:7 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:8 http://deb.debian.org/debian stretch-backports InRelease [91.8 kB]
Hit:9 http://mirror.hetzner.de/debian/packages stretch Release
Hit:10 http://deb.debian.org/debian stretch Release
Get:11 http://mirror.hetzner.de/debian/packages stretch-updates/main amd64 Packages [7688 B]
Get:12 http://mirror.hetzner.de/debian/packages stretch-updates/main Translation-en [5096 B]
Get:13 http://security.debian.org stretch/updates/main amd64 Packages [329 kB]
Get:14 http://security.debian.org stretch/updates/main Translation-en [145 kB]
Get:15 http://security.debian.org stretch/updates/contrib amd64 Packages [1776 B]
Get:16 http://security.debian.org stretch/updates/contrib Translation-en [1759 B]
Ign:17 http://mirror.hetzner.de/debian/packages stretch-backports/main amd64 Packages
Ign:18 http://mirror.hetzner.de/debian/packages stretch-backports/main Translation-en
Ign:19 http://mirror.hetzner.de/debian/packages stretch-backports/contrib amd64 Packages
Ign:20 http://mirror.hetzner.de/debian/packages stretch-backports/contrib Translation-en
Ign:21 http://mirror.hetzner.de/debian/packages stretch-backports/non-free amd64 Packages
Ign:22 http://mirror.hetzner.de/debian/packages stretch-backports/non-free Translation-en
Get:17 http://mirror.hetzner.de/debian/packages stretch-backports/main amd64 Packages [275 kB]
Get:18 http://mirror.hetzner.de/debian/packages stretch-backports/main Translation-en [193 kB]
Get:19 http://mirror.hetzner.de/debian/packages stretch-backports/contrib amd64 Packages [6424 B]
Get:20 http://mirror.hetzner.de/debian/packages stretch-backports/contrib Translation-en [5227 B]
Get:21 http://mirror.hetzner.de/debian/packages stretch-backports/non-free amd64 Packages [18.1 kB]
Get:22 http://mirror.hetzner.de/debian/packages stretch-backports/non-free Translation-en [24.0 kB]
Get:23 http://mirror.hetzner.de/debian/security stretch/updates/main amd64 Packages [329 kB]
Get:24 http://mirror.hetzner.de/debian/security stretch/updates/main Translation-en [145 kB]
Get:25 http://mirror.hetzner.de/debian/security stretch/updates/contrib amd64 Packages [1776 B]
Get:26 http://mirror.hetzner.de/debian/security stretch/updates/contrib Translation-en [1759 B]
Get:27 http://deb.debian.org/debian stretch-updates/main amd64 Packages [7688 B]
Get:28 http://deb.debian.org/debian stretch-updates/main Translation-en [5096 B]
Get:29 http://deb.debian.org/debian stretch-backports/main amd64 Packages [275 kB]
Get:30 http://deb.debian.org/debian stretch-backports/main Translation-en [193 kB]
Get:31 http://deb.debian.org/debian stretch-backports/contrib amd64 Packages [6424 B]
Get:32 http://deb.debian.org/debian stretch-backports/contrib Translation-en [5227 B]
Get:33 http://deb.debian.org/debian stretch-backports/non-free amd64 Packages [18.1 kB]
Get:34 http://deb.debian.org/debian stretch-backports/non-free Translation-en [24.0 kB]
Fetched 2515 kB in 3s (790 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  sudo
0 upgraded, 1 newly installed, 0 to remove and 7 not upgraded.
Need to get 1,055 kB of archives.
After this operation, 3,108 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian stretch/main amd64 sudo amd64 1.8.19p1-2.1 [1,055 kB]
Fetched 1,055 kB in 0s (12.1 MB/s)
Selecting previously unselected package sudo.
(Reading database ... 27470 files and directories currently installed.)
Preparing to unpack .../sudo_1.8.19p1-2.1_amd64.deb ...
Unpacking sudo (1.8.19p1-2.1) ...
Setting up sudo (1.8.19p1-2.1) ...

Configuration file '/etc/sudoers'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** sudoers (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package sudo (--configure):
 end of file on stdin at conffile prompt
Processing triggers for systemd (232-25+deb9u1) ...
Processing triggers for man-db (2.7.6.1-2) ...
Errors were encountered while processing:
 sudo
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by AlexZeitler** [comment]
Sorry for the late answer, currently I'm getting this error when using the debian image:

```
Setting Docker configuration on the remote daemon...
Error creating machine: Error running provisioning: ssh command error:
command : sudo systemctl -f start docker
err     : exit status 1
output  : Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
```

**Comment by monochromata** [comment]
These problems all seem to be caused by the machine image `debian-9` that we use by default. The machine image is created by Hetzner. We do not maintain the machine image and hence cannot fix these issues that arise when the image is used with Docker machine to create a new machine.

May I ask you (@AlexZeitler and @tiii) to create support tickets with Hetzner cloud at https://console.hetzner.cloud/support and let us know when they solved the issue or in case we can be of further help? Maybe you can include a link to this issue so the Hetzner cloud team can access the existing context.

@tiii can you proceed with another machine image, e.g. `--hetzner-image=ubuntu-16.04` or is this issue a blocker for you?

We (@JonasProgrammer and @mxschmitt) might consider using another machine image as default (and document the default values in README.md). I work with `centos-7`. Do you have any other preferences? `ubuntu-16.04` might be better because dependencies can be installed using `apt`, like under Debian.

I will change the title of the issue (I assume the issue is not limited to or caused by macOS).

**Comment by mxschmitt** [comment]
Hi there,
I could not reproduce this issue (not a mac), the only thing that struck me about the hcloud boxes is that sometimes on the first boot apt is locked (`Could not get lock /var/lib/dpkg/lock`), so it is used maybe by hcloud to update the lists?
But I don't think, that this is relevant to this issue. 

Also I tried to setup a fresh vm with `debian-9` and installed `sudo` like three posts above mentioned in the logs. The result of that is, that `sudo` was already installed.

**Comment by JonasProgrammer** [comment]
So I just deployed a test machine and while the `sudo` installation worked out perfectly (the `sudoers` file should not be in place in the latest image versions at the time of asking in the hetzner forums back when this issue was originally created), so I cannot reproduce your results @tiii.
Just for information purpose, have you tried deploying more than once? And if so, have you limited your attempts to a certain datacenter or server tier? The only reasonable explanation I currently have is, that some datacenter/tier constellation somehow still uses the old image with the abandoned `sudoers` file, making further unattended installations impossible.

As for the `systemd` error, I now get that too with the latest image and docker versions. However, it surely did work with some older version, when I re-tested it 23 days ago.

**Comment by tiii** [comment]
I tried multiple times and never specified a datacenter or a specific machine, so the defaults are used. I even retried it yesterday and got the same result. I'm using the ubuntu image right now., so it's not a stopper for me.

**Comment by monochromata** [comment]
Ok, the new release 1.0.0 defaults to the `ubuntu-16.04` image. If anyone received notice from Hetzner that the `debian-9` work again (and is able to verify that it actually does) please mention it here so we can close this issue. :-)

**Comment by mxschmitt** [comment]
I'll close this issue now, because there was no response after 26 days, so we think, that the error doesn't come up anymore.

**Comment by frankier** [comment]
I still get the error with debian-9. The problem is that aufs is not installed in the kernel. I recommend explicitly documenting how to use another storage driver. See: https://github.com/JonasProgrammer/docker-machine-driver-hetzner/pull/13
